---
- hosts: all
  become: yes
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Install gnome
      apt: name={{ item }} state=installed
      with_items:
        - xorg
        - gnome-core
        - gnome-system-tools
        - gnome-app-install

    - name: Install iperf
      apt: name=iperf

    - name: Install sip-tester
      apt: name=sip-tester

    - name: Install linphone
      apt: name=linphone

    - name: Install iptables
      apt: name=iptables-persistent

    - name: Delete default eth0
      shell: "ip route del default dev eth0"

    - name: Add default eth1
      shell: "ip route add default via 10.10.2.1 dev eth1"

    - name: copy iptables
      copy:
        src: iptablesRulesServer
        dest: /etc/iptables/rules.v4
        owner: root
        group: root
        mode: 0644
      notify: "restore iptables"

  handlers:
    - name: restore iptables
      shell: iptables-restore /etc/iptables/rules.v4
      listen: "restore iptables"
