---
- hosts: all
  become: yes
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Install iperf
      apt: name=iperf

    - name: Install sip-tester
      apt: name=sip-tester

    - name: Install iptables
      apt: name=iptables-persistent

    - name: Delete default eth0
      shell: "ip route del default dev eth0"

    - name: Add default eth1
      shell: "ip route add default via 10.10.1.1 dev eth1"

    - name: Copy iptables rules
      copy:
        src: iptablesRulesClient
        dest: /etc/iptables/rules.v4
        owner: root
        group: root
        mode: 0644
      notify: "restore iptables"

    - name: Copy docs (1)
      copy:
        src: g711a.pcap
        dest: /home/vagrant/g711a.pcap

    - name: Copy docs (2)
      copy:
        src: dtmf_2833_1.pcap
        dest: /home/vagrant/dtmf_2833_1.pcap

  handlers:
    - name: restore iptables
      shell: iptables-restore /etc/iptables/rules.v4
      listen: "restore iptables"
